### ISSUE TITLE
Creating chemCPA environemnt

### ISSUE THREAD

**Issue by v-mahughes** [theislab/chemCPA#105]
I am having issues setting up the chemCPA environment. I cloned the repo onto my machine and executed the command: 'conda env create -f environment.yml.' I get the following error: 

Solving environment: failed

ResolvePackageNotFound: 
  - moses

So I removed moses and RDKit from the .yml file. I then run 'conda env create -f environment.yml.' again, with the intention to install MOSES / Rdkit manually after it is done running via these instructions found on the MOSES github repo: 

'The simplest way to install MOSES (models and metrics) is to install [RDKit](https://www.rdkit.org/docs/Install.html): conda install -yq -c rdkit rdkit and then install MOSES (molsets) from pip (pip install molsets). If you want to use LatentGAN, you should also install additional dependencies using bash install_latentgan_dependencies.sh.

If you are using Ubuntu, you should also install sudo apt-get install libxrender1 libxext6 for RDKit.'

However, it gets stuck on 'Solving Environment.' Please let me know how I should proceed!

**Comment by tuln128** [comment]
Hi,
I think the simplest way is to adjust the content of the environment.yml file. Instead of removing package **moses**, you'd better move that line below **pip:**, like this:

(_Do not work_)
**dependencies:
- moses**
--->
(_Should work_)
**- pip:
   - moses**
 
Hope it helps,

**Comment by siboehm** [comment]
Sorry for responding so late to this issue, I must've completely missed it when you posted it. Both moses and sfaira aren't part of the `environment.yml` anymore, if anyone else is having issues setting up this environment on Linux / Mac then I'm happy to help.
