### ISSUE TITLE
Can not find “lincs_full.h5ad” file

### ISSUE THREAD

**Issue by guoyangming-dean** [theislab/chemCPA#106]
Hi, we can't find  "lincs_full.h5ad" file and we can not generate "lincs_full_pp.h5ad". Can you release the source file or links?

**Comment by siboehm** [comment]
Sorry for noticing this issue so late, it must've slipped through. We're working making the source datasets better available, but for now, here's a link to download [lincs_full.h5ad].(https://drive.google.com/file/d/13nsaHS4X09UmXQxelBCf4quleWqFEXNq/view?usp=share_link)

**Comment by reem12345** [comment]
Hello,
I raised a new issue, could you check it please?

**Comment by siboehm** [comment]
Link to the LINCS dataset download has been added to readme

**Comment by bhomass** [comment]
apparently there is a lincs_full.h5ad and a lincs.h5ad. Only link to lincs_full.h5ad is provided in README.
