### ISSUE TITLE
Finetuning to SciPlex dataset.

### ISSUE THREAD

**Issue by reem12345** [theislab/chemCPA#108]
When I try to finetune from LINCS to SciPlex, I got an error because the covariates embedding of LINCS has [82,32] and SciPlex includes only 3 cell lines.

**Comment by siboehm** [comment]
Thanks for raising another issue! If you want help, please post as much context as possible. Which code where you running? What was the error that you got? How did you setup the datasets?

**Comment by reem12345** [comment]
I trained the model on LINCS Dataset. and I want to fine-tune on SciPlex dataset. But I got this error: 
RuntimeError: Error(s) in loading state_dict for Embedding:
	size mismatch for weight: copying a param with shape torch.Size([82, 32]) from checkpoint, the shape in current model is torch.Size([3, 32]).

**Comment by siboehm** [comment]
IIRC in our experiments we do not carry over the covariates when finetuning a LINCS models, but retrain a new embedding from scratch (the embedding is so small anyway).

Without seeing any code I can't really help you more here.

**Comment by MxMstrmn** [comment]
Simon is correct, the shapes you describe correspond to the cell line embeddings and we did not transfer those for fine-tuning. Removing the embedding with shape torch.Size([82, 32])  should resolve the issue.
