### ISSUE TITLE
fail in running the rdkit hparam for lincs

### ISSUE THREAD

**Issue by huawen-poppy** [theislab/chemCPA#113]
Dear developers, thanks for your inspiring tools!

When I tried to run the config_lincs_rdkit_hparam_sweep.yaml file using seml under the experiments/lincs_rdkit_hparam directory, I failed. The error shows like below:
![image](https://user-images.githubusercontent.com/70507602/216827922-f63afa29-19e3-4a26-ac37-470b9a6440c8.png)

Then I have a check on the config_lincs_rdkit_hparam_sweep.yaml file. I found its executable file is set to chemCPA/seml_sweep_icb.py, which doesn't exist. Could you please guide me to run the process correctly? Thank you very much for your help in advance!

**Comment by siboehm** [comment]
Yeah you should probably point it: https://github.com/theislab/chemCPA/blob/main/chemCPA/experiments_run.py instead. We must've renamed it.

Be sure to set up seml properly (if you want to use their functionality for tracking the experiments), instructions are in their repo: https://github.com/TUM-DAML/seml

**Comment by huawen-poppy** [comment]
I see. Thank you for your reply!
