### ISSUE TITLE
Provide dataset to run an individual training round

### ISSUE THREAD

**Issue by ggonzalezp** [theislab/chemCPA#115]
Hello, 
You mentioned you provide the file `manual_seml_sweep.py` to run experiments manually. This one uses the dataset `simon/config_sciplex3_interactive.yaml`, could you provide this dataset for me to be able to use the script, please? I tried with other datasets and it doesn't work out of the box
Thank you

**Comment by MxMstrmn** [comment]
Hi @ggonzalezp, I provided a fix for your problem. It should work now! Thanks for your interest in our work :)

**Comment by Hrovatin** [comment]
The link can not be used without requesting access. I would need chemCPA/embeddings/rdkit/data/embeddings/rdkit2D_embedding_lincs_trapnell.parquet
