### ISSUE TITLE
Can't find drugbank_all.csv

### ISSUE THREAD

**Issue by sumanabasu** [theislab/chemCPA#117]
Hi
Where do I find the `drugbank_all.csv` file? It's not with the raw datasets.

**Comment by MxMstrmn** [comment]
Please see the updated README.md from #119 - the csv can also be provided upon request

**Comment by bhomass** [comment]
"the csv can also be provided upon request" - do you mean we can request this file from you? I would like to get a copy.

**Comment by rvinas** [comment]
How was this file downloaded from Drug Bank? It would be great to have clear instructions. Thank you!

**Comment by bhomass** [comment]
I applied for license and spoke to their sales team. It isn't free most of the time.
