### ISSUE TITLE
Reproducibility issues

### ISSUE THREAD

**Issue by regloeb** [theislab/chemCPA#121]
Congratulations for the great paper and thank you for the amazing work.

I am trying to reproduce some of the experiments and I am really struggling.

Is there a way to run experiments without slurm ? I am trying to use the script `chemCPA/manual_seml_sweep.py`with the config file 'config_lincs_rdkit_hparam_sweep.yaml` and I am getting several bugs.
I am using the datasets prepared by the notebooks in the `preprocessing` directory and there seems to be some inconsistency with what the experiment above is expecting.

Some guidance would be greatly appreciated.

Kind regards

**Comment by jasperhyp** [comment]
Hi @regloeb were you successful?  I've been trying to do the same thing without `seml` and that proves to be hard.  Would appreciate some pointers to essentially make the model training!
