### ISSUE TITLE
where is GSE92742_Broad_LINCS_pert_info.txt

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#126]
GSE92742_Broad_LINCS_pert_info.txt is used in lincs_SMILES.ipynb. is this downloadable anywhere? I really wonder how everybody else got so far with all these missing data.

**Comment by bhomass** [comment]
found on NIH site.

**Comment by Simonhuang233333** [comment]
how can i get it

**Comment by Simonhuang233333** [comment]
ok got it
