### ISSUE TITLE
cell_id or cell_type for dataset.data_params.covariate_keys

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#129]
There are a few .yaml files which declare
dataset.data_params.covariate_keys: cell_id

most declare
dataset.data_params.covariate_keys: cell_type

but the code in data.py
```
for i in range(len(self)):
    drug = indx(self.drugs_names, i)
    cov = indx(self.covariate_names["cell_type"], i)
```
has hard coding expecting cell_type.

Should I assume all instances of "cell_id" need to be converted to "cell_type"?

turns out they are one and the same in value
adata.obs['cell_type'] = adata.obs['cell_id']

**Comment by MxMstrmn** [comment]
Hi @bhomass, 

Can you give more detail on the dataset you are referring to? I assume the Sciplex data? I agree that this bit of the code needs some refactoring. To give a bit more context: chemCPA is designed to operate with any number of covariates but requires the `cell_type` one, which should always be present.

**Comment by bhomass** [comment]
Any yaml file with covariants_key set to cell_id needs to be changed to cell_type. There are many such yaml files throughout the repo. This is independent of which dataset. Like you said, the data.py code is fixed to look for cell_type.
