### ISSUE TITLE
bug in embedding.py

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#136]
this line in embedding.py

`emb = torch.tensor(df.loc[smiles].values, dtype=torch.float32, device=device)`

couldn't possibly have worked. smiles is a list, not a single value. 

it seems what you want is
`emb = torch.tensor(df[df.index.isin(smiles)].values, dtype=torch.float32, device=device)`

However the following assert fails
`assert emb.shape[0] == len(smiles)`

I can not verify whether is length check should pass, because both involve original dataset already posted in the repo, for which I have no transparency to the root.

**Comment by MxMstrmn** [comment]
I think it works as expected: 

```python 
import pandas as pd 

d = {f"{i}": [i, i**2, i-3] for i in range(10)}
df = pd.DataFrame.from_dict(d, orient="index")
df.loc[["1", "3"]].values
>>> array([[ 1,  1, -2],
           [ 3,  9,  0]])
```
