### ISSUE TITLE
what is config_hash for?

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#140]
in the notebook section, the use of a config_has is all over the place. seems having to do with matching up with expected pretrained model configs. 

I looked the use of hashlib, but found none.

could someone explain simply why and how this hash is generated and used?

**Comment by bhomass** [comment]
I think this maybe a standard feature of seml?

**Comment by MxMstrmn** [comment]
This is made for convenience and stored during the model training such that we can load models easily and do not overwrite them :)
