### ISSUE TITLE
which molecular embedding was ultimately chosen?

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#143]
Out of the many drug embedding methods, which was behind you published results in fig 2 and 4?

**Comment by MxMstrmn** [comment]
I am citing this passage from the "Perturbation Network" section of the [paper](https://arxiv.org/pdf/2204.13545.pdf): 
> The molecule encoder G can be any encoding network that maps molecular representations to fixed-size embeddings. Due to the limited number of drugs available in scRNA-seq HTSs, we propose to rely on a pretrained encoding model and freeze G during training. We tested multiple different options for G and include a detailed benchmark in the Appendix A.1. We found that RDKit features performed well in our setting and report all following results for chemCPA with RDKit as the molecule encoder G.

**Comment by bhomass** [comment]
Thank you!
