### ISSUE TITLE
what exactly is your baseline?

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#146]
since I don't have access to the adata_baseline.h5ad file, I can not exam just what you did in the baseline experiment. My guesses are two

1. no pretraining
2. no ood data with drugs not in the training set. 

Could you clarify which one is it?

NVM this. I figured it out and explained below.

**Comment by bhomass** [comment]
My understanding at this point is baseline is unseen combination, but not unseen drug.

**Comment by MxMstrmn** [comment]
The baseline is the prediction of control cells, it indicates if a perturbation had an effect or not. The improved prediction performance on top of the baseline can be attributed to correct perturbation prediction.

**Comment by rvinas** [comment]
My understanding from the paper is that the baseline considers the expression decoded from the basal state (i.e. excluding perturbation information). Am I right in that cell line information was preserved when decoding the control gene expression?

Did you try computing the r2 score between the raw control data (i.e. no autoencoder involved) and the ground-truth post-perturbation profiles predicted by chemCPA?

It would be great if I could get clarification on these points, thank you :)

**Comment by bhomass** [comment]
I see I was not the only one confused. I went through the code, the
baseline is calculated from the truth data vs control. No prediction
involved.

**Comment by rvinas** [comment]
This is not what I understood. I understand that the baseline utilizes the model to decode the basal state.

What I am curious about is: what is the r2 score between the raw control data and the ground-truth post-perturbation profiles? I am guessing that the r2 score might be higher because there is _no information loss_. I think it is important to consider this baseline because there is a strong correlation between post-perturbation profiles and controls.

**Comment by bhomass** [comment]
That's why I was confused about it for a long time also. But the code is
there for you to check.

actually, the r2 would be low (low fidelity) if the perturbation effect is
high. If a drug induces next to no perturbation, then r2 would be high.

**Comment by rvinas** [comment]
I completely agree with your last point.

Did you find where this happens in the code? I cannot see where results from Table 1 are generated.

**Comment by bhomass** [comment]
I don't see table 1 code. but table 4 code shows you the function calls.

**Comment by bhomass** [comment]
This does raise the question. If the baseline is the ground truth, how can the prediction do better? Maybe that's why I was seeing negative Delta R2.

**Comment by bhomass** [comment]
You know, it maybe possible table 4 input dataset_path is an output from a previous experiment instead of raw data. I can't tell because the code reads in configuration from seml database. That would be the only possibility baseline is indeed based on predictions from feeding DMSO into the control input.
