### ISSUE TITLE
how to obtain delta r2 in table 4?

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#155]
table 4 lists improvement of delta r2 of chemCPA over the baseline. 

To replicate this, do you intervene the dose x zd and force its value to 0 for the baseline? or did you fix the perturbation input to be control for drug, 0 for dose, and the same cell line input as the chemCPA sample? 

it seems you are using control samples to generate perturbation predictions. if so, the baseline should just be the same control samples with its real cov_drug_dose, which is DMSO and therefore a non-drug, non-perturbation for its zd. And the output is simply the reconstructed input gene expression, which is the input plus reconstruction error. given a well trained autoencoder, that can easily be approximated by just the input control samples. 

That's what you call baseline? If you could verify this is the case.

**Comment by bhomass** [comment]
I found the code for it. let me figure it out!

**Comment by bhomass** [comment]
there seems to be something very wrong here. in chemCPA_Table_4.ipynb
you have 
drug_r2_pretrained_degs, _ = compute_pred(model_pretrained, 
                                     dataset_all, 
                                     genes_control=datasets['test_control'].genes, 
                                     dosages=dosages,
                                     cell_lines=cell_lines,
                                     use_DEGs=True,
                                     verbose=False,
                                    )

why should you feed genes_control=datasets['test_control'].genes into the pretrained model. This set has multiple cell types. 

The right comparison is matching cell type and dose, as the lines in utils.def compute_pred shows:
        bool_category = pert_categories_index.get_loc(cell_drug_dose_comb)   # <- filtered by cell type and dose
        idx_all = bool2idx(bool_category)
        idx = idx_all[0]
        y_true = dataset.genes[idx_all, :].to(device="cuda") 
 
I see no reason you always use the entire test_control genes as the input set to the model regardless of the cell_drug_dose_comb used as the control signals.

**Comment by MxMstrmn** [comment]
Hi @bhomass, 

This is correct as is, we can feed the entire set of controls as chemCPA learns a disentangled representation. That is, the cell line information from the control cells are removed in the basal embedding. Then, in the latent space, the correct embeddings are added for the perturbation and cell line before decoding again to gene space. Doing it like we did, we are effectively testing the disentanglement ability of the model.
