### ISSUE TITLE
K562 cell type not in L1000. what did you do during fine-tuning?

### ISSUE THREAD

**Issue by bhomass** [theislab/chemCPA#156]
apparently K562 is in sciplex but not L1000. So, the question is during tranfer learning, how were you able to introduce K562 into the cov embedding. You are using one hot encoding for cov, a new cell type would not have a column for you to use during fine tuning.

**Comment by MxMstrmn** [comment]
HI @bhomass, 

We retrained the cell embeddings when transferring from L1000 to sciplex. The transfer was mostly done to get better perturbation embeddings. The sciplex data only has three cell lines so we did not consider transfer learning crucial here. However, in principle this would also be possible.
